// lunchbox.react/src/components/Header.js
import React, { Component } from 'react'

export default class Header extends Component {
    render() {
        return (
            <div className="header-wrapper">
                <div className="back">Back</div>
                <div className="logo">
                    <img src="http://www.lunchbox.dk/assets/images/logo/white.svg" onclick="link_navigation('index');" class="default-icon" alt="" border="0"></img>
                </div>
                <div className="memebership"><i className="fa fa-user"></i><a href="#">Login som medlem</a></div>
            </div>
        )
    }
}

// LunchBox.Angular/src/app/core/components/header.component.ts
import { Component } from '@angular/core';
import { FlexLayoutModule } from '@angular/flex-layout';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [FlexLayoutModule],
  template: `
      <div class="header" fxLayoutAlign="center stretch">
        <div class="main" fxFlex="100" fxFlex.gt-sm="940px" fxLayout="row" fxLayoutAlign="space-between stretch" >
          <div fxLayoutAlign="start center" class="logo"><a routerLink=""><img src="https://www.lunchbox.dk/assets/images/logo/white.svg"></a></div>
          <div fxLayoutAlign="end end" class="user-name">Medlem som Thusi</div>
        </div>
      </div>
    `,
  styles: [`
    
  `]
})
export class HeaderComponent {
}
